# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Homebrew/bin/cmake

# The command to remove a file.
RM = /usr/local/Homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/bhavyapatel/Documents/CS/Projects/pcie_testing-main

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/bhavyapatel/Documents/CS/Projects/pcie_testing-main

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/Homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/Homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/local/Homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/local/Homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/local/Homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/local/Homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/local/Homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/local/Homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bhavyapatel/Documents/CS/Projects/pcie_testing-main/CMakeFiles /Users/bhavyapatel/Documents/CS/Projects/pcie_testing-main//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bhavyapatel/Documents/CS/Projects/pcie_testing-main/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pcie_tests

# Build rule for target.
pcie_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pcie_tests
.PHONY : pcie_tests

# fast build rule for target.
pcie_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pcie_tests.dir/build.make CMakeFiles/pcie_tests.dir/build
.PHONY : pcie_tests/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

src/debugfs_handler.o: src/debugfs_handler.cpp.o
.PHONY : src/debugfs_handler.o

# target to build an object file
src/debugfs_handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pcie_tests.dir/build.make CMakeFiles/pcie_tests.dir/src/debugfs_handler.cpp.o
.PHONY : src/debugfs_handler.cpp.o

src/debugfs_handler.i: src/debugfs_handler.cpp.i
.PHONY : src/debugfs_handler.i

# target to preprocess a source file
src/debugfs_handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pcie_tests.dir/build.make CMakeFiles/pcie_tests.dir/src/debugfs_handler.cpp.i
.PHONY : src/debugfs_handler.cpp.i

src/debugfs_handler.s: src/debugfs_handler.cpp.s
.PHONY : src/debugfs_handler.s

# target to generate assembly for a file
src/debugfs_handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pcie_tests.dir/build.make CMakeFiles/pcie_tests.dir/src/debugfs_handler.cpp.s
.PHONY : src/debugfs_handler.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pcie_tests.dir/build.make CMakeFiles/pcie_tests.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pcie_tests.dir/build.make CMakeFiles/pcie_tests.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pcie_tests.dir/build.make CMakeFiles/pcie_tests.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/pcie_test.o: src/pcie_test.cpp.o
.PHONY : src/pcie_test.o

# target to build an object file
src/pcie_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pcie_tests.dir/build.make CMakeFiles/pcie_tests.dir/src/pcie_test.cpp.o
.PHONY : src/pcie_test.cpp.o

src/pcie_test.i: src/pcie_test.cpp.i
.PHONY : src/pcie_test.i

# target to preprocess a source file
src/pcie_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pcie_tests.dir/build.make CMakeFiles/pcie_tests.dir/src/pcie_test.cpp.i
.PHONY : src/pcie_test.cpp.i

src/pcie_test.s: src/pcie_test.cpp.s
.PHONY : src/pcie_test.s

# target to generate assembly for a file
src/pcie_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pcie_tests.dir/build.make CMakeFiles/pcie_tests.dir/src/pcie_test.cpp.s
.PHONY : src/pcie_test.cpp.s

src/usb/usb_manager.o: src/usb/usb_manager.cpp.o
.PHONY : src/usb/usb_manager.o

# target to build an object file
src/usb/usb_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pcie_tests.dir/build.make CMakeFiles/pcie_tests.dir/src/usb/usb_manager.cpp.o
.PHONY : src/usb/usb_manager.cpp.o

src/usb/usb_manager.i: src/usb/usb_manager.cpp.i
.PHONY : src/usb/usb_manager.i

# target to preprocess a source file
src/usb/usb_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pcie_tests.dir/build.make CMakeFiles/pcie_tests.dir/src/usb/usb_manager.cpp.i
.PHONY : src/usb/usb_manager.cpp.i

src/usb/usb_manager.s: src/usb/usb_manager.cpp.s
.PHONY : src/usb/usb_manager.s

# target to generate assembly for a file
src/usb/usb_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pcie_tests.dir/build.make CMakeFiles/pcie_tests.dir/src/usb/usb_manager.cpp.s
.PHONY : src/usb/usb_manager.cpp.s

src/usb_test.o: src/usb_test.cpp.o
.PHONY : src/usb_test.o

# target to build an object file
src/usb_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pcie_tests.dir/build.make CMakeFiles/pcie_tests.dir/src/usb_test.cpp.o
.PHONY : src/usb_test.cpp.o

src/usb_test.i: src/usb_test.cpp.i
.PHONY : src/usb_test.i

# target to preprocess a source file
src/usb_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pcie_tests.dir/build.make CMakeFiles/pcie_tests.dir/src/usb_test.cpp.i
.PHONY : src/usb_test.cpp.i

src/usb_test.s: src/usb_test.cpp.s
.PHONY : src/usb_test.s

# target to generate assembly for a file
src/usb_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pcie_tests.dir/build.make CMakeFiles/pcie_tests.dir/src/usb_test.cpp.s
.PHONY : src/usb_test.cpp.s

src/utils/fs_helper.o: src/utils/fs_helper.cpp.o
.PHONY : src/utils/fs_helper.o

# target to build an object file
src/utils/fs_helper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pcie_tests.dir/build.make CMakeFiles/pcie_tests.dir/src/utils/fs_helper.cpp.o
.PHONY : src/utils/fs_helper.cpp.o

src/utils/fs_helper.i: src/utils/fs_helper.cpp.i
.PHONY : src/utils/fs_helper.i

# target to preprocess a source file
src/utils/fs_helper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pcie_tests.dir/build.make CMakeFiles/pcie_tests.dir/src/utils/fs_helper.cpp.i
.PHONY : src/utils/fs_helper.cpp.i

src/utils/fs_helper.s: src/utils/fs_helper.cpp.s
.PHONY : src/utils/fs_helper.s

# target to generate assembly for a file
src/utils/fs_helper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pcie_tests.dir/build.make CMakeFiles/pcie_tests.dir/src/utils/fs_helper.cpp.s
.PHONY : src/utils/fs_helper.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... pcie_tests"
	@echo "... src/debugfs_handler.o"
	@echo "... src/debugfs_handler.i"
	@echo "... src/debugfs_handler.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/pcie_test.o"
	@echo "... src/pcie_test.i"
	@echo "... src/pcie_test.s"
	@echo "... src/usb/usb_manager.o"
	@echo "... src/usb/usb_manager.i"
	@echo "... src/usb/usb_manager.s"
	@echo "... src/usb_test.o"
	@echo "... src/usb_test.i"
	@echo "... src/usb_test.s"
	@echo "... src/utils/fs_helper.o"
	@echo "... src/utils/fs_helper.i"
	@echo "... src/utils/fs_helper.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

